## Object Oriented Programming
### Introduction to OOP in Python
One of the popular approch to solve a programming problem by creating an objects. This is known as object oriented programming.<dr>
    
An objects has two characteristics:<dr>
1. attributes (name,age,colour)<dr>
2. behaviour (learn, study, singing, dancing)<dr>

In python, the concept oop follows these things<dr>
    1. Inheritance
    2. encapsulation
    3. polymorphism
    
Class : 

a class is blueprint for the object or logical entity

Object : 

blue print of the class or instance of the class or physical entity

Methods :

part of class and can be called with object



In [5]:
def test():
    print("test() for function")
    return
test()

test() for function


In [17]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
    
obj=Demo()
obj.test()

test() for the class and method


In [22]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        print(fact)
    
p1=Demo1()
p1.fact(5)

120


In [28]:
class Demo2:
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def add(self,p1,p2):
        return p1+p2
c1=Demo2()
print(c1.add(10,20))

30


In [35]:
# Some Inheritance 
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
class Employee(person):
    def isemployee(self):
        return True
    
emp=person("anil")
print(emp.getname(),emp.isemployee())

emp1=Employee("akhil")
print(emp1.getname(),emp1.isemployee())

anil False
akhil True


## Python numPy
NumPy arrays is a bit like python list

Numpy array is a central datastructure of the numpy lib

This lib actually short for "numberic python" or "numerical python"

In [41]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [42]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [39]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [40]:
lst=[1.8,2.46,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [43]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [49]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(6,1)

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [53]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [54]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [55]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [57]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [11]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=15
print(A)

[[ 1  1  1  1]
 [ 1  1  1  1]
 [15 15 15 15]
 [ 1  1  1  1]]


In [12]:
import numpy as np
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [2]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [5]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row: ",a1[0])

first row:  [1 2 3]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row: ",a1[1])

second row:  [4 5 6]


In [17]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,2])

slicing column: [3 6]


In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and column",a1[1,:1])

Row and column [4]


In [19]:
a1=np.random.normal(5,1,10)
print(a1)

[5.80275149 4.64220461 4.83568651 4.94054314 5.14775917 4.30989842
 5.39652786 2.75237733 5.3608086  4.12483225]


In [23]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value:",np.min(a1))
print("max value",np.max(a1))
print("mean value",np.mean(a1))
print("median value",np.median(a1))

[4.91976806 4.30517051 5.00018721 5.31320602 4.86383292 7.12440551
 5.76113518 5.4626697  5.35140625 4.35265143]
min value: 4.305170514265882
max value 7.124405505336339
mean value 5.245443279615111
median value 5.156696616310091


In [24]:
# multiply of 1d array
# numpy.dot(x,y)
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [26]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(1,2),(5,7)])
np.dot(c1,c2)

array([[11, 16],
       [23, 34]])

In [28]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

## Pandas Basics
python is one of the popular pr-ogramming language for data analysis<br> 

Panda DataFrames

Data Analysis with python
    

In [29]:
import pandas as pd
dict={"name":["anil","akhil","dinesh","harsha","ajay","kranth"],
      "emailid":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com",
                 "harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
      "mobile":[999,222,456,485,258,265]} 
b=pd.DataFrame(dict)
print(b)

     name           emailid  mobile
0    anil    anil@gmail.com     999
1   akhil   akhil@gmail.com     222
2  dinesh  dinesh@gmail.com     456
3  harsha  harsha@gmail.com     485
4    ajay    ajay@gmail.com     258
5  kranth  kranth@gmail.com     265


In [30]:
b.index=["01","02","03","04","05","06"]
print(b)

      name           emailid  mobile
01    anil    anil@gmail.com     999
02   akhil   akhil@gmail.com     222
03  dinesh  dinesh@gmail.com     456
04  harsha  harsha@gmail.com     485
05    ajay    ajay@gmail.com     258
06  kranth  kranth@gmail.com     265


In [31]:
import calendar
a=calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [48]:
def frequency(a):
    i=0
    while(i<=9):
        count=0
        for j in range(len(a)):
            if(ord(a[j])>=48 and ord(a[j])<=56):
                if i==int(a[j]):
                    count=count+1
        print(count,end=" ")
        i=i+1
a="213abc456def111"
frequency(a)

0 4 1 1 1 1 1 0 0 0 

In [53]:
def anogram(a,b):
    i=0
    count=0
    for i in range(len(a)):
        for j in range(len(b)):
            if(ord(b[j])>=97 and ord(b[j])<=122):
                if a[i]==a[j]:
                    count=count+1
    if(count==len(a) or count==len(b)):
        print("true")

a="abcde"
b="abc"
anogram(a,b)

true
